### ISSUE TITLE
Updated release build?

### ISSUE THREAD

**Issue by v3suvious** [Arsunt/TR2Main#14]
There's lots of stuff in the changelog that's not in the current release. Any chance you could do a new release, please? Or alternatively provide instructions on how to build ourselves, as I have no clue how to do that :)

**Comment by Arsunt** [comment]
Hey! I'll upload the stable release to github after redesigning FMV playback. But you can always get the fresh developer's build for beta testers on Discord channel: https://discord.gg/JAp9Pg8

**Comment by vaibhavrmahadevan** [comment]
@Arsunt I would love to join the Discord server :)

**Comment by StenApp** [comment]
> Hey! I'll upload the stable release to github after redesigning FMV playback. But you can always get the fresh developer's build for beta testers on Discord channel: https://discord.gg/JAp9Pg8

Your link doesn‘t work ☹️

**Comment by VoodaGod** [comment]
found a newer build here: https://drive.google.com/drive/folders/1Ap7mHU6PYIKR79za9ocjCuF6UWFgSLNo
in this post: https://www.tombraiderforums.com/showpost.php?p=8206492&postcount=7

**Comment by aaronat4am** [comment]
> found a newer build here: https://drive.google.com/drive/folders/1Ap7mHU6PYIKR79za9ocjCuF6UWFgSLNo in this post: https://www.tombraiderforums.com/showpost.php?p=8206492&postcount=7

The link now goes to an empty folder. Any chance to get the last build? The latest 0.8.2 posted here is missing some good working features, like the pix folder, the controller options and the resolution fixes. Hope it can be uploaded soon as it improves the game a lot!

**Comment by StenApp** [comment]
@Arsunt  is this project still active? It looks like you abandoned it. ☹️

**Comment by VoodaGod** [comment]
here is the version i still had lying around from https://www.tombraiderforums.com/showpost.php?p=8206492&postcount=7:
https://1drv.ms/u/s!AuK9tjeI0Y6njqx-bl5FJmmRMcCQPw?e=3cfjdw

**Comment by StenApp** [comment]
Thank you VoodaGod for the file.
I‘m looking forward for a more recent version than 2021. We have 2023…

**Comment by Arsunt** [comment]
Github release was updated. Sorry for long waiting.
