### ISSUE TITLE
XINPUT1_3.dll missing

### ISSUE THREAD

**Issue by Richard-L** [Arsunt/TR2Main#17]
I see this had been brought up before and you had even responded: https://discord.com/channels/218414493355606016/394838132643725314/756351112444903504

Would be nice to have them included if that's possible. I'm also running into this issue.

Many thanks!

**Comment by Richard-L** [comment]
I followed the link you had posted on discord to obtain **directx_Jun2010_redist.exe** from http://www.microsoft.com/en-us/download/confirmation.aspx?id=8109

I did not want to install in order not to pollute my system, so I extracted **XINPUT1_3.dll** from the downloaded archive, and placed it into the Tomb2-Main folder.

It then prompts this error:

![image](https://user-images.githubusercontent.com/4934209/103456992-a0033880-4cfb-11eb-8f6c-216c0b9584b9.png)

Is there any chance you could make Tomb2-Main work more standalone, without depending on installing other things first?

Many thanks for your consideration.

**Comment by Arsunt** [comment]
Hello! Thank you for the reporting. I've fixed this in https://github.com/Arsunt/TR2Main/commit/1857d14fb5bb429460ba91a90db2e2aa6ce84ed7

**Comment by Arsunt** [comment]
Hello! Thank you for the reporting. I've fixed this in https://github.com/Arsunt/TR2Main/commit/1857d14fb5bb429460ba91a90db2e2aa6ce84ed7
