### ISSUE TITLE
Music and FMVs are not working on Steam version

### ISSUE THREAD

**Issue by rr-** [Arsunt/TR2Main#19]
I'm using the latest release
- FMVs aren't played.
- Music doesn't work in the main menu.
- Music doesn't work in individual levels.
- Lara doesn't say anything in the training level.

**Comment by Arsunt** [comment]
FMV will be enabled in the next big release after FMV playback rework.

About music and cut scenes.
- What localization do you use?
- Make sure there is **cdaudio.dat** and **cdaudio.mp3** in **audio** subfolder.
- Make sure there is no WINMM.DLL (left from some wrapper) in your game folder.

**Comment by rr-** [comment]
Thanks for the fast response.

1. I tried:
    - `C:\Program Files (x86)\Steam\Steamapps\common\Tomb Raider (II)`
    - `C:\users\rr-\@\games\TR2` (no spaces)

    Same thing
2. Both files are present
3. There was `WINMM.DLL`, I removed it but music is still not playing in the main menu.

**Comment by Arsunt** [comment]
- Both files in **audio** subfolder?
- Check the music volume in-game
- Some Windows systems have problems with built-in audio codecs. Probably [codec pack](https://codecguide.com/download_kl.htm) will help in this case.

**Comment by rr-** [comment]
1) Yes
2) It's set to 10
3) Will try in a second

**Comment by rr-** [comment]
It was a matter of missing codecs. Thank you!
