### ISSUE TITLE
Secret bug in Catacombs of the Talion

### ISSUE THREAD

**Issue by EtherealMalice** [Arsunt/TR2Main#28]
I've been doing a run with all secrets and no medipacks and have made to near the end of the snow levels. I noticed once I got the orange dragon secret that it never gave the bonus items you normally get when you acquire all of the secret in a given level. I checked the statistics and the white dragon secret just disappears. I noticed it when I went back through and got the green dragon secret, the slot where the white one is supposed to be is indented out but empty. And it doesn't acknowledge it when you finish the level, it's just empty. So far this has been then only level to do this.

**Comment by Arsunt** [comment]
Hey! What exact version of TR2Main did you use? Do you have a saved video of your run?

**Comment by EtherealMalice** [comment]
I've been using the one from here https://drive.google.com/drive/folders/1Ap7mHU6PYIKR79za9ocjCuF6UWFgSLNo
No I don't have a recording of it, but I can try and make one if you'd like.

**Comment by EtherealMalice** [comment]
https://www.youtube.com/watch?v=oQM_XqPS3E4 Here's a link to the recording. It's strange it didn't appear neither that time nor the one I just did. Maybe it's just a rare bug. And here's a link to a recording of just the last part of the save file where it for sure happened. https://www.youtube.com/watch?v=ImFKYQqj544

**Comment by Arsunt** [comment]
Please could you provide me your saved games. Specifically I want the one numbered 148 with missing silver secret.

**Comment by EtherealMalice** [comment]
Here is a link to the saves https://drive.google.com/drive/folders/1M8HJh1fTsBY5drNzLfQHM_mXP5-9dlR5?usp=sharing
That save should be number 12 in that list

**Comment by Arsunt** [comment]
Hey, @EtherealMalice ! I have bad news for you, you just missed the first secret. You can fly back to it using Dozy mode; here are some files to enable it https://drive.google.com/file/d/1Wga7gV6FeSJN75qcUI-PxJ3Ev-wfAAcw 

If cheats are enabled, hit "I" to get all weapons, ammo, keys, etc. Or press "O" to fly ("Walk" button to land).

Here is the video https://drive.google.com/file/d/1TL8uYzjOX19_i2FCFHRY1QQr-IvOVw7R

Also I did recheck the code and it is nearly impossible to accidentally corrupt just one bit in statistics, and also to recover two items in their places (flarebox and silver secret).

**Comment by EtherealMalice** [comment]
Ah ok, I was sure I picked it up, I might have just thought I did. That's good to know.
Thank you for checking into it <3. I'll close the issue now.
