### ISSUE TITLE
development aborded ?

### ISSUE THREAD

**Issue by ghost** [Arsunt/TR2Main#3]
hello arsunt,
i love this project because tr2 is really bugged in pc,
the development is aborded or too long ?
praticaly sure that is school or life cause it but impossible to escape :x

**Comment by Arsunt** [comment]
Hello! Of course no. I just have few months of break. Right now I'm finishing brand new FMV and audio playback.

**Comment by ghost** [comment]
thanks for this news
and good luck for fmv :)
