### ISSUE TITLE
Patch have viruses

### ISSUE THREAD

**Issue by MrRaf99** [Arsunt/TR2Main#30]
https://www.virustotal.com/gui/file/fbd0844cb82a8cb0defa08aa28081f194a9f2d3f59ea5204fab9d106453b419c/detection
Not good.

**Comment by bisousmwah** [comment]
That's actually a **false** positive, sometimes, cheat or injector programs use **Trojan** to inject **code** in your files like **TRA** for example.

**Comment by Arsunt** [comment]
It is false positive. The patch has no viruses, you can review all the code and build it yourself to make sure.
