### ISSUE TITLE
[Linux] Helicopter cinematic, black screen with audio

### ISSUE THREAD

**Issue by legluondunet** [Arsunt/TR2Main#37]
Hello,
I just tested TR2Main more recent version available here: https://www.tombraiderforums.com/showpost.php?p=8206492&postcount=7
I saw TR2Main now uses directx9 that is fully supported on Linux with Wine/DXVK.
I would like to know what did you change for playing cinematics cause with DXVK they do not play correctly: I obtain black screen and I can hear audio. I do not know if it is a DXVK bug.  Do you have a more recent build so I can test if I can reproduce this issue with latest TR2Main code.
Thank you for your help.

**Comment by noisecode3** [comment]
It works with wine and proton perfectly with widescreen FMV, seems stable. I played 10 min.
Try with [conty](https://github.com/Kron4ek/Conty)
You have to extract with unzip command into gamedir and overwrite Tomb2.exe
Then make sure it have cd into gamedir and try `conty.sh wine  Tomb2.exe`

That's it, no wine overrides or other patches.

**Comment by legluondunet** [comment]
This issue was caused mainly by dgVoodoo2, my old TR2 installed used dgVoodoo2 to play cinematics and game in fullscreen, that is no more necessary with latest TR2Main and even conflict with it. I reinstall TR2 without dgVoodoo2 and now logo and intro video play correctly.
But...
When you begin a new game, you have the helicopter cinematic and I can hear sound but screen is all black.
I found that if I inactivate DXVK, this cinematic plays correctly.

**Comment by legluondunet** [comment]
@noisecode3 could you tell me if you can reproduce this issue? 
Can you see helicopter cinematic with DXVK on?
I wrote a Lutris script to install TR2 (GOG and Steam version) with Arsunt TR2Main, you can find it here
https://lutris.net/games/tomb-raider-ii

**Comment by noisecode3** [comment]
Yes the first FMV with the helicopter is a black screen. That only happens with wine from lutris or its you're script. With proton DXVK it ran bad, it was like it was lagging on my good computer. If it's proton or just DXVK problem don't know. But with `conty.sh wine Tomb2.exe` it ran good. Is sound a little weird? The camera distance sound with headphones when the camera zoomed in it got 4 times more volume and when the camera is far I almost only could hear the background sound. It sound cool a bit too much with headphones maybe or could it be another wine/proton bug?

EDIT: The sound problem was a broken cable lol, it somehow messed with the stereo sound XD

**Comment by noisecode3** [comment]
Hey, maybe Gallium Nine could be a hit :)

EDIT: gallimu nine seem to only do some magic on my disable Nvidia laptop with Quadro K2100M with nouveau cus nvidia dropped driver support for new kernels after 5.4.

on my good compute with amd rx590 gallium did not matter.
on both computers, compiled wine-tkg seemed to run the game best.

CSMT was disable on both computers. I'm not sure it matter but it could be that the game would freeze or crash when you die or exit a menu. 

I could test some more tonight, I have to do my programming homework before tomorrow.

**Comment by legluondunet** [comment]
With csmt off, helicopter cinematic still black and I don't think CSMT is still an active option in Wine,  it is indicated as deprecated in winecfg option.
Something strange is the 2 intro cinematic playing ok, but not the helicopter. I think only @Arsunt  should know why.

**Comment by noisecode3** [comment]
Helicopter cinematic works with newer wine from lutris, I don't think DXVK works for this game. It makes the camera stuttering or not feel smooth. It's not frame drops reported by something like mongohud but is visible bad.  CSMT is deprecated and we can forget about it. WINED3D and gallium nine are working really good with wine-tkg and camera is smooth. When I disable DXVK in lutris with default wine Helicopter cinematic work. But there is strange colors when dark in the game, like some filter is not right, it looks like its only 16 colors in the dark part of the map lol.  Something wrong with lutris wine?

Other problems I found on all wine
Sound buffer plays 1 second of last sound. For example when the games starts. there is 1 second of menu sound before the background sound starts. This happens in game also from map to map or last "scene soundtrack".

When I don't have my controller I use h,j,k,l vim keys to move, lol and I noticed when walk was set to "s or d" it only worked walking to the forward/right but not forward/left. If I used shift or arrow keys there was not problem.
But when I defined them with custom keys like that I could only walk forward/right.

**Comment by noisecode3** [comment]
Found solution to the audio problem.
With winetricks install quartz_feb2010
and also use WINEDLLOVERRIDES="winmm=n,b"

**Comment by noisecode3** [comment]
I found the perfect parameters to run the game. That keyboard problem was a xfce4-keyboard-settings bug not related  to the game or wine for this game. So here it is. This works for me.

Download wine-tkg or build it in you home by running [non-makepkg-build.sh](https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/non-makepkg-build.sh). Then with winetricks run `winetricks quartz_feb2010` maybe in a new clean prefix like `WINEPREFIX=~/.steam/root/steamapps/common/Tomb\ Raider\ \(II\)/PRX` then `cd ~/.steam/root/steamapps/common/Tomb\ Raider\ \(II\)/` or you'll get shell could not run error. Then DONT run with fsync or esync because even on my strong computer it would result in rare minor stuttering usually in the beginning. For me this is completely stutter free even on my bad computer, and no bugs for me. With WINED3D

### How I run on my big strong computer
```
WINEDLLOVERRIDES="winmm=n,b" \
WINEFSYNC=0 \
WINEESYNC=0 \
wine Tomb2.exe
```

### My personal script for weak laptop 

```
#!/bin/bash
cd ~/.steam/root/steamapps/common/Tomb\ Raider\ \(II\)/
pkill picom # You xorg compositor
WINEPREFIX=~/.steam/root/steamapps/common/Tomb\ Raider\ \(II\)/PRX \
WINEDLLOVERRIDES="winmm=n,b" \
STAGING_RT_PRIORITY_SERVER=90 \
STAGING_SHARED_MEMORY=1 \
mesa_glthread=true \
WINEFSYNC=0 \
WINEESYNC=0 \
DRI_PRIME=0 \
wine Tomb2.exe
picom --vsync &
```

**Comment by legluondunet** [comment]
I'm surprise you need to install quartz dll...

**Comment by noisecode3** [comment]
It was some `fixme:quartz:DSoundRender BUFFER_COULD_NOT_BE_STOPPED_SOMETHING_DON'T_REMEMBER_NOW`. It will fix 1 sec sound from menu when you start the game. If you don't `WINEDLLOVERRIDES="winmm=n,b"` it will play the background in a 5 sec loop at some point in the game. Will you confirm this happens at you end? :)

**Comment by noisecode3** [comment]
The bug that makes the audio loop is reproducible, at opera house when you climb a ladder after being in the water it plays a different audio clip while climbing. After that, the background audio gets struck in a  about 5 sec loop
![screenshot](https://user-images.githubusercontent.com/3844376/222010664-17478677-2525-4efd-a270-aedd07eb8c2b.png)

**Comment by legluondunet** [comment]
can not reproduce this issue with latest Wine 8.7 GE PROTON version and TR2MAIN developer version.
