### ISSUE TITLE
new feature: GOLD - Howto?

### ISSUE THREAD

**Issue by legluondunet** [Arsunt/TR2Main#5]
Hello,
I saw in changelog you added a new feature: if I start the exe with "-gold" option, it could start the gold version. But how and where to add necessary files? Is it possible to have the two version in the same tree?

**Comment by Arsunt** [comment]
Hey! It is supposed to have both versions in the same tree. This weekend I plan to finish the master of the migration of saved games, it will give the opportunity to automatically copy all the saved games into new separate folders (for separating the saves of gold and non-gold versions) and work with them using these folders only. This is the only thing left to do to complete the work of the Golden Mask. In order for everything to work, you need to copy some files from the "Golden Mask" data folder into the TR2 "data" folder. Some of the copied files must first be renamed by adding the suffix "g" to the file name.

Here is the current file structure.
"Golden mask" files, that just copied are __bold__.
"Golden mask" files, that copied and renamed are __*bold italic*__.
Be careful, the game uses original TITLE.TR2 and ASSAULT.TR2 in both Gold and non-Gold.

* audio *(this folder is optional if real AudioCD used, or winmm.dll+fmodex.dll wrapper used)*
    - cdaudio.dat
    - cdaudio.mp3
* data
    - TOMBPC.DAT
    - __*TOMBPCg.DAT*__
    - __CREDIT00.PCX__
    - CREDIT01.PCX
    - CREDIT02.PCX
    - CREDIT03.PCX
    - CREDIT04.PCX
    - CREDIT05.PCX
    - CREDIT06.PCX
    - CREDIT07.PCX
    - __*CREDIT07g.PCX*__
    - CREDIT08.PCX
    - CREDIT09.PCX
    - END.PCX
    - LEGAL.PCX
    - __LEGALg.PCX__
    - TITLE.PCX
    - __TITLEg.PCX__
    - MAIN.SFX
    - __*MAINg.SFX*__
    - ASSAULT.TR2 *(don't use the Gold version of this file)*
    - BOAT.TR2
    - CATACOMB.TR2
    - CUT1.TR2
    - CUT2.TR2
    - CUT3.TR2
    - CUT4.TR2
    - DECK.TR2
    - EMPRTOMB.TR2
    - FLOATING.TR2
    - HOUSE.TR2
    - ICECAVE.TR2
    - KEEL.TR2
    - __LEVEL1.TR2__
    - __LEVEL2.TR2__
    - __LEVEL3.TR2__
    - __LEVEL4.TR2__
    - __LEVEL5.TR2__
    - LIVING.TR2
    - MONASTRY.TR2
    - OPERA.TR2
    - PLATFORM.TR2
    - RIG.TR2
    - SKIDOO.TR2
    - TITLE.TR2 *(don't use the Gold version of this file)*
    - UNWATER.TR2
    - VENICE.TR2
    - WALL.TR2
    - XIAN.TR2
* fmv
    - ANCIENT.RPL
    - CRASH.RPL
    - JEEP.RPL
    - END.RPL
    - LANDING.RPL
    - LOGO.RPL
    - MODERN.RPL
    - MS.RPL
* pix *(this folder is optional but it provides possibility to use HD pictures of proper aspect ratio. TR2Main supports "PNG", "JPG", "BMP", "PCX". It uses proper available aspect ratio automatically)*
    * 5x4
    * 4x3
        - LEGAL.PNG
        - LEGALg.PNG
        - TITLE.PNG
        - TITLEg.PNG
        - ... *(any of your remastered images, for example 1600x1200)*
    * 3x2
    * 16x10
    * 16x9
        - LEGAL.PNG
        - LEGALg.PNG
        - TITLE.PNG
        - TITLEg.PNG
        - ... *(any of your remastered images, for example 1920x1080)*
    * 21x9
    * 32x9

**Comment by Arsunt** [comment]
Remastered title for TR2Gold can be found [here](https://www.tombraiderforums.com/showthread.php?t=221596)

**Comment by legluondunet** [comment]
Very exciting work!!!! The mod feature is great too!!!
I noted this new feature is not yet complete as you are working on saves game functionnality.
For audio and cinematics, do you know if there are differences between TR2 and TR2 Gold?

**Comment by Arsunt** [comment]
Thank you. I'm doing my best.
There is no separate CD Audio and FMV for TR2 Gold. It uses original game assets.

**Comment by legluondunet** [comment]
Thank you took time to answer this questions, I can close this issue.

**Comment by legluondunet** [comment]
Hello Arsunt, I tried to launch the Golden mask extension with:
Tomb2.exe -gold
but I obtained a black screen instead of the main menu.

I copied all files and renamed them as you described:
TOMBPCg.DAT in main game golder
and the others in DATA folder.

**Comment by legluondunet** [comment]
I finally had time to try this new feature and I can't make it work.

I added this files to data folder:
credit00.pcx
credit07g.PCX
legalg.PCX
level1.tr2
level2.tr2
level3.tr2
level4.tr2
level5.tr2
MAINg.SFX
titleg.pcx
tombPCg.dat

launched with -gold option, but this launches only normal level.
Could you help me please?

**Comment by legluondunet** [comment]
hello Arsunt, did you still have work to do on this new feature or it is already finished, with separate saved game files?

**Comment by Arsunt** [comment]
Hello! Sorry for late answer. Just separate subfolders added, no migration wizard yet, though not released, just pushed. Recently I've returned to the project and I plan to prepare new official release.

**Comment by legluondunet** [comment]
Good news, so I will let this issue opened until I test the next release.

**Comment by Instandhaltung** [comment]
Hey Arsunt, noob here! I tried TR2Main with the golden mask. The game plays, but without music and ambient sounds. Do you have an idea what I can do? I installed the golden mask with this tutorial: https://www.tombraiderforums.com/showthread.php?t=211383&highlight=golden+mask+perfectly

**Comment by MateusAuri** [comment]
Using the latest release (20210403), applied to the GOG version, I can attest that it works perfectly!
I just copied the files as instructed by Arsunt and added the -gold argument.

**Comment by legluondunet** [comment]
just tested TR2 Gold with latest release 20210920, it works as expected.
