### ISSUE TITLE
Inv_RingRotateLeft/Right Wrong Name

### ISSUE THREAD

**Issue by ghost** [Arsunt/TR2Main#7]
I'm working on inventory.cpp
Inv_RingRotateLeft_425300 and Inv_RingRotateRight_425330 have name inversed or it's just me ?!
an example:

```
if (InputStatus & IN_RIGHT && ring.objCount > 1)
{
    Inv_RingRotateRight(&ring);
    PlaySoundEffect(0x6Cu, 0, SFX_ALWAYS);
    continue;
}
```
move to left !

```
if (InputStatus & IN_LEFT && ring.objCount > 1)
{
    Inv_RingRotateLeft(&ring);
    PlaySoundEffect(0x6Cu, 0, SFX_ALWAYS);
    continue;
}
```
move to right !

IN_RIGHT is for left and same for IN_LEFT  that are right ?
in the database, Inv_RingRotateLeft is in IN_RIGHT and Right is in IN_LEFT !

PS: GFF_Unknown is GFF_HOME_ENABLED ;)

**Comment by Arsunt** [comment]
No, the function names are correct. Core Design named them in such way, and this means, when you press RIGHT, the ring rotates LEFT, and vice versa.

**Comment by ghost** [comment]
ok thanks :)
